# Generated by Django 4.1.3 on 2023-04-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="description",
            field=models.TextField(default=None),
        ),
    ]
