# Generated by Django 4.1.3 on 2023-01-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_order_created_at_order_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="percentage_pl",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="profit_loss",
            field=models.IntegerField(default=0),
        ),
    ]
